### PR TITLE
Added "is24HourView" option for android devices time picker

### PR DESCRIPTION
**Pull request by dfabreguette**
I needed to get rid of the "AM/PM" to switch to french time formatting so I just added the option the plugin options.

### CODE REVIEW

**Comment by hafl1016** [comment]
Hi all,
Is this functionality already added at the moment?
How am I able to change the view of the timepicker form 12h to 24h formatting?
regards

**Comment by dfabreguette-ap** [comment]
Simply use set the option "setIs24HourView" to true to disable AM/PM format :
```
datePicker.show({
  date: defaultDate,
  mode: mode,
  is24HourView: true,
  ...
})
```

**Comment by loiclefloch** [comment]
Why this pull request didn't pull ?

@hafl1016 For the moment you can use the @dfabreguette-ap modifications with 
cordova plugin add https://github.com/dfabreguette-ap/cordova-plugin-datepicker
I have also forked this repository, and add the support for the new Android datepicker here https://github.com/loiclefloch/cordova-plugin-datepicker.git

**Comment by hafl1016** [comment]
@loiclefloch Thank you
I tried both plugins and have to decide now which one I'm going to use
Thanks to you both

**Comment by VitaliiBlagodir** [comment]
Option is24Hour added in v0.8.0

**Comment by roysG** [comment]
i have version 0.9.3 and this option not working, also the max and min date not working,

**Pull request closed without merging**
